name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chromium, firefox, webkit]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        BROWSER: ${{ matrix.browser }}
      run: npx playwright test --project=${{ matrix.browser }} --reporter=html
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ matrix.os }}-${{ matrix.browser }}
        path: playwright-report/
        retention-days: 30

  consolidate-report:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download all reports
      uses: actions/download-artifact@v4
      with:
        path: all-reports
    - name: Merge Playwright reports
      run: |
        npx playwright merge-reports all-reports/**/playwright-report
        npx playwright show-report
    - uses: actions/upload-artifact@v4
      with:
        name: consolidated-playwright-report
        path: playwright-report/
        retention-days: 30
