name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chromium, firefox, webkit]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npm install playwright@1.52.0
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        BROWSER: ${{ matrix.browser }}
      run: npx playwright test --project=${{ matrix.browser }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: blob-report-${{ matrix.os }}-${{ matrix.browser }}
        path: blob-report/
        retention-days: 30

  consolidate-report:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npm install playwright@1.52.0
    - name: Download all reports
      uses: actions/download-artifact@v4
      with:
        path: all-blob-reports
        pattern: blob-report-*
        merge-multiple: false
      
    - name: List downloaded reports
      run: ls -R all-blob-reports

    - name: Extract all blob reports to merged directory
      run: |
        mkdir -p merged-blob-reports
        find all-blob-reports -type f -name "*.zip" -exec unzip -o {} -d merged-blob-reports \;
    
    - name: List extracted reports
      run: |
        echo "Extracted blob reports:"
        ls -R merged-blob-reports

    - name: Find blob report files
      run: |
        echo "Looking for blob report files..."
        find merged-blob-reports -type f -name "*.jsonl" || echo "No .jsonl files found"
        find merged-blob-reports -type f -name "trace.zip" || echo "No trace.zip files found"
        find merged-blob-reports -type f -name "*.trace" || echo "No .trace files found"

    - name: Merge into HTML Report
      run: |
        echo "Merging reports..."
        npx playwright merge-reports --reporter html merged-blob-reports

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 14
